using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace WeaponSpeedReachForwarder;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "Settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "WeaponSpeedReachForwarder.esp")
            .Run(args);
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var weaponMods = _settings.Value.WeaponModPlugin.ToHashSet();

        if (weaponMods.Count == 0)
            return;

        foreach (var weaponMod in weaponMods)
        {
            var index = state.LoadOrder.IndexOf(weaponMod);

            if (index < 0 || !state.LoadOrder[index].Enabled || state.LoadOrder[index].Mod is null)
                throw new Exception($"{weaponMod} isn't loaded");
        }

        var weapons = new Dictionary<FormKey, IWeaponGetter>();

        foreach (var mod in state.LoadOrder.ListedOrder)
        {
            if (!mod.Enabled || mod.Mod is null || !weaponMods.Contains(mod.ModKey))
                continue;

            foreach (var weapon in mod.Mod.EnumerateMajorRecords<IWeaponGetter>())
                weapons[weapon.FormKey] = weapon;
        }

        var winners = state.LoadOrder.PriorityOrder
            .Weapon()
            .WinningOverrides()
            .ToDictionary(x => x.FormKey);

        var patched = 0;

        foreach (var (formKey, source) in weapons)
        {
            if (source.Data is null || !winners.TryGetValue(formKey, out var winner))
                continue;

            var weapon = state.PatchMod.Weapons.GetOrAddAsOverride(winner);

            if (weapon.Data is null)
                continue;

            if (weapon.Data.Speed == source.Data.Speed && weapon.Data.Reach == source.Data.Reach)
                continue;

            weapon.Data.Speed = source.Data.Speed;
            weapon.Data.Reach = source.Data.Reach;
            patched++;
        }

        Console.WriteLine($"Patched {patched} weapon speed/reach records");
    }
}
