using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace WeaponSpeedReachForwarder;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "Settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "WeaponSpeedReachForwarder.esp")
            .Run(args);
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var weaponMods = _settings.Value.WeaponModPlugin.ToHashSet();

        if (weaponMods.Count == 0)
            return;

        var weapons = new Dictionary<FormKey, IWeaponGetter>();

        foreach (var mod in state.LoadOrder.ListedOrder)
        {
            if (!mod.Enabled || mod.Mod is null || !weaponMods.Contains(mod.ModKey))
                continue;

            foreach (var weapon in mod.Mod.EnumerateMajorRecords<IWeaponGetter>())
                weapons[weapon.FormKey] = weapon;
        }

        foreach (var weaponMod in weaponMods)
            if (!state.LoadOrder.Any(x => x.ModKey == weaponMod && x.Enabled && x.Mod is not null))
                throw new Exception($"{weaponMod} isn't loaded");

        var winners = state.LoadOrder.PriorityOrder
            .Weapon()
            .WinningContextOverrides(state.LinkCache)
            .ToDictionary(x => x.Record.FormKey);

        var patchWeapons = state.PatchMod
            .EnumerateMajorRecords<IWeaponGetter>()
            .ToDictionary(x => x.FormKey);

        var patched = 0;

        foreach (var (formKey, source) in weapons)
        {
            if (source.Data is null || !winners.TryGetValue(formKey, out var winner))
                continue;

            var current = patchWeapons.TryGetValue(formKey, out var patchWeapon)
                ? patchWeapon
                : winner.Record;

            if (current.Data is null ||
                current.Data.Speed == source.Data.Speed && current.Data.Reach == source.Data.Reach)
                continue;

            var weapon = winner.GetOrAddAsOverride(state.PatchMod);

            if (weapon.Data is null)
                continue;

            weapon.Data.Speed = source.Data.Speed;
            weapon.Data.Reach = source.Data.Reach;
            patchWeapons[formKey] = weapon;
            patched++;
        }

        Console.WriteLine($"Patched {patched} weapon speed/reach records");
    }
}
