using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace WeaponSpeedReachForwarder;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "Settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "WeaponSpeedReachForwarder.esp")
            .Run(args);
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var weaponMods = _settings.Value.WeaponModPlugin.ToHashSet();

        foreach (var weaponMod in weaponMods)
        {
            var index = state.LoadOrder.IndexOf(weaponMod);

            if (index < 0 || !state.LoadOrder[index].Enabled || state.LoadOrder[index].Mod is null)
                throw new Exception($"{weaponMod} isn't loaded");
        }

        var selectedWeapons = new Dictionary<FormKey, IWeaponGetter>();

        foreach (var mod in state.LoadOrder.ListedOrder)
        {
            if (!mod.Enabled || mod.Mod is null || !weaponMods.Contains(mod.ModKey))
                continue;

            foreach (var weapon in mod.Mod.EnumerateMajorRecords<IWeaponGetter>())
                selectedWeapons[weapon.FormKey] = weapon;
        }

        var winners = state.LoadOrder.PriorityOrder
            .Weapon()
            .WinningOverrides()
            .ToDictionary(x => x.FormKey);

        if (_settings.Value.UseReqtificatorSettings)
        {
            var origins = new Dictionary<FormKey, IWeaponGetter>();

            foreach (var mod in state.LoadOrder.ListedOrder)
            {
                if (!mod.Enabled || mod.Mod is null)
                    continue;

                foreach (var weapon in mod.Mod.EnumerateMajorRecords<IWeaponGetter>())
                    if (weapon.FormKey.ModKey == mod.ModKey)
                        origins[weapon.FormKey] = weapon;
            }

            var patched = 0;

            foreach (var (formKey, winner) in winners)
            {
                if (winner.Data is null || winner.Data.AnimationType == WeaponAnimationType.Bow || winner.Data.AnimationType == WeaponAnimationType.Crossbow)
                    continue;

                float speed;
                float reach;

                if (selectedWeapons.TryGetValue(formKey, out var selected) && selected.Data is not null)
                {
                    speed = selected.Data.Speed;
                    reach = selected.Data.Reach;
                }
                else
                {
                    if (!origins.TryGetValue(formKey, out var origin) || origin.Data is null)
                        continue;

                    speed = origin.Data.Speed;
                    reach = origin.Data.Reach;

                    switch (origin.Data.AnimationType)
                    {
                        case WeaponAnimationType.HandToHand:
                        case WeaponAnimationType.OneHandSword:
                        case WeaponAnimationType.OneHandDagger:
                        case WeaponAnimationType.OneHandAxe:
                        case WeaponAnimationType.OneHandMace:
                        case WeaponAnimationType.TwoHandSword:
                        case WeaponAnimationType.TwoHandAxe:
                            reach *= 0.7f;
                            break;
                    }
                }

                if (winner.Data.Speed == speed && winner.Data.Reach == reach)
                    continue;

                var weapon = state.PatchMod.Weapons.GetOrAddAsOverride(winner);

                if (weapon.Data is null)
                    continue;

                weapon.Data.Speed = speed;
                weapon.Data.Reach = reach;
                patched++;
            }

            Console.WriteLine($"Patched {patched} weapon speed/reach records");
            return;
        }

        if (selectedWeapons.Count == 0)
            return;

        var patchedDirect = 0;

        foreach (var (formKey, source) in selectedWeapons)
        {
            if (source.Data is null || source.Data.AnimationType == WeaponAnimationType.Bow || source.Data.AnimationType == WeaponAnimationType.Crossbow || !winners.TryGetValue(formKey, out var winner))
                continue;

            var weapon = state.PatchMod.Weapons.GetOrAddAsOverride(winner);

            if (weapon.Data is null)
                continue;

            if (weapon.Data.Speed == source.Data.Speed && weapon.Data.Reach == source.Data.Reach)
                continue;

            weapon.Data.Speed = source.Data.Speed;
            weapon.Data.Reach = source.Data.Reach;
            patchedDirect++;
        }

        Console.WriteLine($"Patched {patchedDirect} weapon speed/reach records");
    }
}
